In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Data.csv')

In [4]:
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, 3].values

In [5]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

In [8]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [13]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.5)

In [33]:
print(x_train)

[[0.0 0.0 1.0 0.09615548262427409 -0.7301244449756336]
 [0.0 1.0 0.0 1.4085478806042302 1.579452880967697]
 [0.0 0.0 1.0 -1.2812068360477593 -1.0281344225167084]
 [0.0 1.0 0.0 -0.9303692643105432 -0.5811194562050961]
 [1.0 0.0 0.0 0.7068727371297981 0.759925442729741]]


In [27]:
print(x_test)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [28]:
print(y_train)

[0 0 1 0 0]


In [29]:
print(y_test)

[1 1 0 1 1]


In [30]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train[:,3:]=sc.fit_transform(x_train[:,3:])
x_test[:,3:]=sc.transform(x_test[:,3:])

In [31]:
print(x_train)

[[0.0 0.0 1.0 0.09615548262427409 -0.7301244449756336]
 [0.0 1.0 0.0 1.4085478806042302 1.579452880967697]
 [0.0 0.0 1.0 -1.2812068360477593 -1.0281344225167084]
 [0.0 1.0 0.0 -0.9303692643105432 -0.5811194562050961]
 [1.0 0.0 0.0 0.7068727371297981 0.759925442729741]]


In [32]:
print(x_test)

[[0.0 1.0 0.0 0.23908930814684348 0.1473493777841984]
 [1.0 0.0 0.0 -0.3456399780818499 -0.2831094786640212]
 [0.0 0.0 1.0 0.0051975936553661445 -0.05960199550821498]
 [1.0 0.0 0.0 -0.11174826359037253 0.38741297080339737]
 [1.0 0.0 0.0 1.1746561661127528 1.2814429034266221]]
